import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Project from './Project'
import Experience from './Experience'

export default function Home({ datas }) {
  return (
    <div >
      <Head>
        <title>Prakash-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <img src={datas.avatar_url} alt="myavtar" />
        <h1>{datas.name}</h1>
        <p>{datas.login}</p>
        <h4>{datas.bio}</h4>
        <button><a href="https://drive.google.com/file/d/1u5p6FVjlCirFgfi8xIipA-BvdIZuM3fU/view?usp=sharing">Resume</a></button>
        <button><a href="https://github.com/Prakash6204">Follow</a></button>
      </main>
      <Experience />
    </div>
  )
}
export async function getServerSideProps() {
  const res = await fetch(`https://api.github.com/users/Prakash6204`)
  const data = await res.json()
  console.log(data)
  return {
    props: {
      datas: data,
    }
  }
}
